
import type { Dish, Table } from '@/types';

export const initialDishes: Dish[] = [
  // 经济快餐 (Economy Fast Food) - New Category
  { id: 'dish-95', name: '木耳肉丝', price: 15.00, category: '经济快餐', imageHint: 'woodear pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-96', name: '香干肉丝', price: 15.00, category: '经济快餐', imageHint: 'driedtofu pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-97', name: '肉沫茄子', price: 15.00, category: '经济快餐', imageHint: 'pork eggplant', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-98', name: '韭菜炒肉丝', price: 13.00, category: '经济快餐', imageHint: 'chives pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-99', name: '青椒炒腊肉', price: 18.00, category: '经济快餐', imageHint: 'pepper curedpork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-100', name: '煎豆腐炒肉', price: 15.00, category: '经济快餐', imageHint: 'friedtofu pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-101', name: '四季豆炒肉', price: 13.00, category: '经济快餐', imageHint: 'greenbean pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-102', name: '香芹炒肉丝', price: 13.00, category: '经济快餐', imageHint: 'celery pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-103', name: '香干回锅肉', price: 15.00, category: '经济快餐', imageHint: 'tofu twicecooked', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-104', name: '豆角炒肉丝', price: 12.00, category: '经济快餐', imageHint: 'beans pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-105', name: '苦瓜炒肉片', price: 15.00, category: '经济快餐', imageHint: 'bittermelon pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-106', name: '蒜苔炒腊肉', price: 18.00, category: '经济快餐', imageHint: 'garlicscape pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-107', name: '蒜苔炒肉丝', price: 15.00, category: '经济快餐', imageHint: 'garlicscape pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-108', name: '莴笋炒腊肉', price: 18.00, category: '经济快餐', imageHint: 'lettuce curedpork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-109', name: '油豆腐炒肉', price: 15.00, category: '经济快餐', imageHint: 'tofupuff pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-110', name: '尖椒回锅肉', price: 15.00, category: '经济快餐', imageHint: 'chili twicecooked', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-111', name: '土豆片回锅肉', price: 15.00, category: '经济快餐', imageHint: 'potato twicecooked', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-112', name: '酸辣鸡杂', price: 15.00, category: '经济快餐', imageHint: 'spicy gizzards', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-113', name: '炒红薯叶', price: 12.00, category: '经济快餐', imageHint: 'sweetpotato leaves', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-114', name: '尖椒鸡杂', price: 15.00, category: '经济快餐', imageHint: 'chili gizzards', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-115', name: '外婆菜肉沫', price: 15.00, category: '经济快餐', imageHint: 'grandma pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-116', name: '香芹炒猪肝', price: 15.00, category: '经济快餐', imageHint: 'celery liver', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-117', name: '尖椒炒猪心', price: 15.00, category: '经济快餐', imageHint: 'chili heart', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-118', name: '烟笋炒腊肉', price: 18.00, category: '经济快餐', imageHint: 'bamboo curedpork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-119', name: '香芹炒鸡杂', price: 15.00, category: '经济快餐', imageHint: 'celery gizzards', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-120', name: '香芹炒猪心', price: 15.00, category: '经济快餐', imageHint: 'celery heart', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-121', name: '干豆角炒腊肉', price: 20.00, category: '经济快餐', imageHint: 'beans curedpork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-122', name: '干豆角炒鸡杂', price: 18.00, category: '经济快餐', imageHint: 'beans gizzards', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-123', name: '冬菇滑鸡', price: 18.00, category: '经济快餐', imageHint: 'mushroom chicken', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-124', name: '炒小鱼仔', price: 28.00, category: '经济快餐', imageHint: 'small fish', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-125', name: '农家一碗香', price: 25.00, category: '经济快餐', imageHint: 'farmhouse bowl', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-126', name: '香菇炒肉', price: 28.00, category: '经济快餐', imageHint: 'mushroom pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-127', name: '青椒肉丝', price: 25.00, category: '经济快餐', imageHint: 'pepper pork', imagePath: 'https://placehold.co/300x200.png' },

  // 煲类 (Claypot)
  { id: 'dish-9', name: '肉沫茄子煲', price: 22.00, category: '煲类', imageHint: 'pork eggplant', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-10', name: '咸鱼茄子煲', price: 22.00, category: '煲类', imageHint: 'saltedfish eggplant', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-11', name: '鱼香茄子煲', price: 22.00, category: '煲类', imageHint: 'spicy eggplant', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-12', name: '日本豆腐煲', price: 20.00, category: '煲类', imageHint: 'japanese tofu', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-13', name: '金针菇豆腐煲', price: 20.00, category: '煲类', imageHint: 'enoki tofu', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-14', name: '鱼头豆腐煲', price: 35.00, category: '煲类', imageHint: 'fishhead tofu', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-15', name: '冬菇滑鸡煲', price: 35.00, category: '煲类', imageHint: 'mushroom chicken', imagePath: 'https://placehold.co/300x200.png' },
  // 汤类
  { id: 'dish-16', name: '番茄蛋汤', price: 12.00, category: '汤类', imageHint: 'tomato egg', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-17', name: '紫菜蛋汤', price: 12.00, category: '汤类', imageHint: 'seaweed egg', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-18', name: '青菜豆腐汤', price: 12.00, category: '汤类', imageHint: 'vegetable tofu', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-19', name: '酸菜豆腐汤', price: 12.00, category: '汤类', imageHint: 'sour cabbage', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-20', name: '青瓜皮蛋汤', price: 12.00, category: '汤类', imageHint: 'cucumber egg', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-21', name: '玉米排骨汤', price: 38.00, category: '汤类', imageHint: 'corn rib', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-22', name: '酸菜粉丝汤', price: 12.00, category: '汤类', imageHint: 'sour vermicelli', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-23', name: '三鲜汤', price: 15.00, category: '汤类', imageHint: 'mixed soup', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-24', name: '平菇肉片汤', price: 15.00, category: '汤类', imageHint: 'mushroom pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-25', name: '金针菇肉丝汤', price: 15.00, category: '汤类', imageHint: 'enoki pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-26', name: '鱼头豆腐汤', price: 28.00, category: '汤类', imageHint: 'fishhead soup', imagePath: 'https://placehold.co/300x200.png' },
  // 精美小炒
  { id: 'dish-27', name: '蒜蓉菠菜', price: 13.00, category: '精美小炒', imageHint: 'garlic spinach', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-28', name: '蚝油生菜', price: 12.00, category: '精美小炒', imageHint: 'oyster lettuce', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-29', name: '手撕包菜', price: 12.00, category: '精美小炒', imageHint: 'torn cabbage', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-30', name: '蒜蓉菜心', price: 13.00, category: '精美小炒', imageHint: 'garlic choysum', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-31', name: '虎皮尖椒', price: 15.00, category: '精美小炒', imageHint: 'tiger pepper', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-32', name: '蒜蓉油麦菜', price: 12.00, category: '精美小炒', imageHint: 'garlic achoy', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-33', name: '蒜蓉空心菜', price: 12.00, category: '精美小炒', imageHint: 'garlic waterspinach', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-34', name: '麻婆豆腐', price: 13.00, category: '精美小炒', imageHint: 'mapo tofu', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-35', name: '家常豆腐', price: 15.00, category: '精美小炒', imageHint: 'homestyle tofu', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-36', name: '蚂蚁上树', price: 18.00, category: '精美小炒', imageHint: 'ants tree', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-37', name: '干煸四季豆', price: 15.00, category: '精美小炒', imageHint: 'dryfried greenbeans', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-38', name: '回锅肉', price: 25.00, category: '精美小炒', imageHint: 'twicecooked pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-39', name: '青椒炒鸡', price: 30.00, category: '精美小炒', imageHint: 'pepper chicken', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-40', name: '泡椒脆肚', price: 38.00, category: '精美小炒', imageHint: 'pickled tripe', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-41', name: '酸甜排骨', price: 45.00, category: '精美小炒', imageHint: 'sweetour ribs', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-42', name: '爆炒排骨', price: 38.00, category: '精美小炒', imageHint: 'stirfried ribs', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-43', name: '爆炒猪肚', price: 38.00, category: '精美小炒', imageHint: 'stirfried stomach', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-44', name: '蒜苗回锅肉', price: 28.00, category: '精美小炒', imageHint: 'garlicsprout pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-45', name: '粉蒸肉', price: 45.00, category: '精美小炒', imageHint: 'steamed porkrice', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-46', name: '粉蒸排骨', price: 55.00, category: '精美小炒', imageHint: 'steamed ribsrice', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-47', name: '红烧排骨', price: 45.00, category: '精美小炒', imageHint: 'braised ribs', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-48', name: '小炒猪肝', price: 25.00, category: '精美小炒', imageHint: 'stirfry liver', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-49', name: '千页豆腐回锅肉', price: 25.00, category: '精美小炒', imageHint: 'tofu pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-50', name: '泡椒猪肝', price: 28.00, category: '精美小炒', imageHint: 'pickled liver', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-51', name: '爆炒猪肝', price: 25.00, category: '精美小炒', imageHint: 'fried liver', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-52', name: '鱼香肉丝', price: 30.00, category: '精美小炒', imageHint: 'fishfragrant pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-53', name: '青椒炒排骨', price: 35.00, category: '精美小炒', imageHint: 'pepper ribs', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-54', name: '农家小炒肉', price: 25.00, category: '精美小炒', imageHint: 'farmhouse pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-55', name: '烟笋炒腊肉', price: 35.00, category: '精美小炒', imageHint: 'bamboo curedpork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-56', name: '干豆角炒腊肉', price: 40.00, category: '精美小炒', imageHint: 'beancurd curedpork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-57', name: '盐煎肉', price: 30.00, category: '精美小炒', imageHint: 'saltfried pork', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-58', name: '扣肉', price: 35.00, category: '精美小炒', imageHint: 'braised belly', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-59', name: '辣子鸡', price: 30.00, category: '精美小炒', imageHint: 'spicy chicken', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-60', name: '土匪猪肝', price: 30.00, category: '精美小炒', imageHint: 'bandit liver', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-61', name: '椒盐虾', price: 38.00, category: '精美小炒', imageHint: 'saltpepper shrimp', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-62', name: '香辣虾', price: 38.00, category: '精美小炒', imageHint: 'spicy shrimp', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-63', name: '剁椒蒸黄骨鱼', price: 48.00, category: '精美小炒', imageHint: 'chili fish', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-64', name: '大盘鸡', price: 38.00, category: '精美小炒', imageHint: 'bigplate chicken', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-65', name: '红烧猪脚', price: 40.00, category: '精美小炒', imageHint: 'braised trotter', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-66', name: '蒜香骨', price: 48.00, category: '精美小炒', imageHint: 'garlic ribs', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-67', name: '红烧甲鱼', price: 168.00, category: '精美小炒', imageHint: 'braised turtle', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-68', name: '土豆烧排骨', price: 48.00, category: '精美小炒', imageHint: 'potato ribs', imagePath: 'https://placehold.co/300x200.png' },
  // 铁板类 (Teppanyaki / Iron Plate)
  { id: 'dish-69', name: '铁板水晶粉', price: 25.00, category: '铁板类', imageHint: 'teppanyaki crystalnoodles', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-70', name: '铁板肥肠', price: 40.00, category: '铁板类', imageHint: 'teppanyaki porkintestine', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-71', name: '铁板鸡块', price: 32.00, category: '铁板类', imageHint: 'teppanyaki chicken', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-72', name: '铁板田鸡', price: 40.00, category: '铁板类', imageHint: 'teppanyaki frog', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-73', name: '铁板牛肉', price: 45.00, category: '铁板类', imageHint: 'teppanyaki beef', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-74', name: '铁板猪肚', price: 38.00, category: '铁板类', imageHint: 'teppanyaki porkstomach', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-75', name: '铁板腰花', price: 42.00, category: '铁板类', imageHint: 'teppanyaki porkkidney', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-76', name: '铁板黑胡椒牛肉', price: 45.00, category: '铁板类', imageHint: 'teppanyaki blackpepperbeef', imagePath: 'https://placehold.co/300x200.png' },
  // 火锅/鸡煲 (Hot Pot / Chicken Pot)
  { id: 'dish-77', name: '鱼头火锅', price: 68.00, category: '火锅/鸡煲', imageHint: 'fishhead hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-78', name: '鱼火锅', price: 60.00, category: '火锅/鸡煲', imageHint: 'fish hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-79', name: '啤酒鸭火锅', price: 75.00, category: '火锅/鸡煲', imageHint: 'beerduck hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-80', name: '排骨火锅', price: 98.00, category: '火锅/鸡煲', imageHint: 'ribs hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-81', name: '猪脚火锅', price: 88.00, category: '火锅/鸡煲', imageHint: 'trotter hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-82', name: '腊猪脚汤锅', price: 108.00, category: '火锅/鸡煲', imageHint: 'curedtrotter soup', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-83', name: '腊鸭汤锅', price: 75.00, category: '火锅/鸡煲', imageHint: 'curedduck soup', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-84', name: '腊排骨汤锅', price: 108.00, category: '火锅/鸡煲', imageHint: 'curedribs soup', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-85', name: '牛杂火锅', price: 98.00, category: '火锅/鸡煲', imageHint: 'beefoffal hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-86', name: '牛肚火锅', price: 108.00, category: '火锅/鸡煲', imageHint: 'beeftripe hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-87', name: '烧鸡公火锅', price: 75.00, category: '火锅/鸡煲', imageHint: 'roastchicken hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-88', name: '牛腩火锅', price: 98.00, category: '火锅/鸡煲', imageHint: 'beefbrisket hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-89', name: '狗肉火锅', price: 148.00, category: '火锅/鸡煲', imageHint: 'dogmeat hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-90', name: '羊肉火锅', price: 138.00, category: '火锅/鸡煲', imageHint: 'mutton hotpot', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-91', name: '麻辣烤鱼', price: 58.00, category: '火锅/鸡煲', imageHint: 'spicy grilledfish', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-92', name: '香辣烤鱼', price: 58.00, category: '火锅/鸡煲', imageHint: 'fragrantspicy grilledfish', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-93', name: '泡椒烤鱼', price: 65.00, category: '火锅/鸡煲', imageHint: 'pickledchili grilledfish', imagePath: 'https://placehold.co/300x200.png' },
  { id: 'dish-94', name: '甲鱼煲', price: 148.00, category: '火锅/鸡煲', imageHint: 'turtle pot', imagePath: 'https://placehold.co/300x200.png' },
];

export const initialTables: Table[] = [
  { id: 'table-1', number: '1', order: [] },
  { id: 'table-2', number: '2', order: [] },
  { id: 'table-3', number: '3', order: [] },
  { id: 'table-4', number: '4', order: [] },
  { id: 'table-5', number: '5', order: [] },
  { id: 'table-6', number: '6', order: [] },
];

    
