import type { Dish, Table } from '@/types';

// Adding a default sortOrder (0) to all dishes. 
// A lower number means it appears higher in the list within its category.
export const initialDishes: Dish[] = [
  // 经济快餐 (Economy Fast Food) - New Category
  { id: 'dish-95', name: '木耳肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-96', name: '香干肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-97', name: '肉沫茄子', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-98', name: '韭菜炒肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-99', name: '青椒炒腊肉', price: 18.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-100', name: '煎豆腐炒肉', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-101', name: '四季豆炒肉', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-102', name: '香芹炒肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-103', name: '香干回锅肉', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-104', name: '豆角炒肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-105', name: '苦瓜炒肉片', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-106', name: '蒜苔炒腊肉', price: 18.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-107', name: '蒜苔炒肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-108', name: '莴笋炒腊肉', price: 18.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-109', name: '油豆腐炒肉', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-110', name: '尖椒回锅肉', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-111', name: '土豆片回锅肉', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-112', name: '酸辣鸡杂', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-113', name: '炒红薯叶', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-114', name: '尖椒鸡杂', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-115', name: '外婆菜肉沫', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-116', name: '香芹炒猪肝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-117', name: '尖椒炒猪心', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-118', name: '烟笋炒腊肉', price: 18.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-119', name: '香芹炒鸡杂', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-120', name: '香芹炒猪心', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-121', name: '干豆角炒腊肉', price: 20.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-122', name: '干豆角炒鸡杂', price: 18.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-123', name: '冬菇滑鸡', price: 18.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-124', name: '炒小鱼仔', price: 28.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-125', name: '农家一碗香', price: 25.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-126', name: '香菇炒肉', price: 28.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-127', name: '青椒肉丝', price: 25.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-128', name: '火腿炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-129', name: '青葱煎蛋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-130', name: '清炒莴笋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-131', name: '番茄炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-132', name: '尖椒煎蛋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-133', name: '苦瓜炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-134', name: '麻辣猪血', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-135', name: '香葱煎蛋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-136', name: '韭菜炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-137', name: '洋葱炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-138', name: '苦瓜煎蛋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-139', name: '香辣炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-140', name: '香芹炒香干', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-141', name: '青椒土豆丝', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-141-1', name: '青瓜炒火腿', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-142', name: '干煸土豆丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-143', name: '醋溜土豆丝', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-144', name: '酸辣土豆丝', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-145', name: '酸豆角肉沫', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-146', name: '酸辣大白菜', price: 12.00, category: '经济快餐', sortOrder: 0 },
  // { id: 'dish-147', name: '蚝油生菜', price: 12.00, category: '经济快餐', sortOrder: 0 },
  // { id: 'dish-148', name: '手撕包菜', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-149', name: '炒上海青', price: 12.00, category: '经济快餐', sortOrder: 0 },
  // { id: 'dish-150', name: '爆炒莲藕', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-151', name: '麻辣藕丁', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-152', name: '家常豆腐', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-153', name: '豆角茄子', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-154', name: '水晶蒸蛋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-155', name: '香葱炒蛋', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-156', name: '麻婆豆腐', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-157', name: '红烧茄子', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-158', name: '红烧豆腐', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-159', name: '香辣四季豆', price: 15.00, category: '经济快餐', sortOrder: 0 },
  // { id: 'dish-160', name: '蒜蓉空心菜', price: 12.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-161', name: '火腿玉米粒', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-164', name: '红萝卜炒肉丝', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-165', name: '红烧日本豆腐', price: 13.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-166', name: '尖椒肉沫炒豆腐', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-167', name: '尖椒荷包蛋', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-168', name: '尖椒肝片', price: 15.00, category: '经济快餐', sortOrder: 0 },
  { id: 'dish-169', name: '攸干炒肉', price: 15.00, category: '经济快餐', sortOrder: 0 },

  // 煲类 (Claypot)
  { id: 'dish-9', name: '肉沫茄子煲', price: 22.00, category: '煲类', sortOrder: 0 },
  { id: 'dish-10', name: '咸鱼茄子煲', price: 22.00, category: '煲类', sortOrder: 0 },
  { id: 'dish-11', name: '鱼香茄子煲', price: 22.00, category: '煲类', sortOrder: 0 },
  { id: 'dish-12', name: '日本豆腐煲', price: 20.00, category: '煲类', sortOrder: 0 },
  { id: 'dish-13', name: '金针菇豆腐煲', price: 20.00, category: '煲类', sortOrder: 0 },
  { id: 'dish-14', name: '鱼头豆腐煲', price: 35.00, category: '煲类', sortOrder: 0 },
  { id: 'dish-15', name: '冬菇滑鸡煲', price: 35.00, category: '煲类', sortOrder: 0 },
  // 汤类
  { id: 'dish-16', name: '番茄蛋汤', price: 12.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-17', name: '紫菜蛋汤', price: 12.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-18', name: '青菜豆腐汤', price: 12.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-19', name: '酸菜豆腐汤', price: 12.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-20', name: '青瓜皮蛋汤', price: 12.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-21', name: '玉米排骨汤', price: 38.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-22', name: '酸菜粉丝汤', price: 12.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-23', name: '三鲜汤', price: 15.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-24', name: '平菇肉片汤', price: 15.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-25', name: '金针菇肉丝汤', price: 15.00, category: '汤类', sortOrder: 0 },
  { id: 'dish-26', name: '鱼头豆腐汤', price: 28.00, category: '汤类', sortOrder: 0 },
  // 精美小炒
  { id: 'dish-27', name: '爆炒鸡杂', price: 25.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-28', name: '香菇炒鸡', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-29', name: '麻辣泥鳅', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-30', name: '小炒田鸡', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-31', name: '麻辣鸡块', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-32', name: '酸甜里脊', price: 42.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-33', name: '红烧鸡块', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-34', name: '酸辣鸡杂', price: 28.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-35', name: '清蒸草鱼', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-36', name: '血旺肥肠', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-37', name: '水煮肉片', price: 35.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-38', name: '豆瓣鱼', price: 33.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-39', name: '葱烧鱼', price: 33.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-40', name: '红烧草鱼', price: 33.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-41', name: '水煮田鸡', price: 42.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-42', name: '小炒牛肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-43', name: '干煸肥肠', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-44', name: '水煮牛肉', price: 48.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-45', name: '爆炒田鸡', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-46', name: '爆炒牛肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  // { id: 'dish-47', name: '爆炒田螺', price: 25.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-47', name: '红烧蹄膀', price: 78.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-48', name: '爆炒四川腊肉', price: 35.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-49', name: '四川麻辣香肠', price: 35.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-50', name: '糖醋全鱼', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-51', name: '红烧肥肠', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-52', name: '姜丝肥肠', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-53', name: '干烧草鱼', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-54', name: '水煮鱼', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-55', name: '毛血旺', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-56', name: '酸菜鱼', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-57', name: '红烧肉', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-58', name: '泡椒田鸡', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-59', name: '泡椒腰花', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-60', name: '麻辣牛肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-61', name: '泡椒肥肠', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-62', name: '剁椒鱼头', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-63', name: '爆炒腰花', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-64', name: '山椒牛肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-65', name: '葱爆牛肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-66', name: '十三香排骨', price: 42.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-67', name: '干煸牛肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-68', name: '水煮毛肚', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-170', name: '爆炒田螺', price: 25.00, category: '精美小炒', sortOrder: 0 }, // Note: Duplicate name, changed ID and hint for differentiation
  { id: 'dish-171', name: '爆炒田螺', price: 25.00, category: '精美小炒', sortOrder: 0 }, 
  { id: 'dish-171-1', name: '爆炒肥肠', price: 40.00, category: '精美小炒', sortOrder: 0 }, // Note: Duplicate name, changed ID and hint
  { id: 'dish-172', name: '四川腊猪舌', price: 48.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-173', name: '泼辣鱼', price: 38.00, category: '精美小炒', sortOrder: 0 },

  // { id: 'dish-198', name: '蒜蓉菠菜', price: 13.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-199', name: '蚝油生菜', price: 12.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-200', name: '手撕包菜', price: 12.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-201', name: '蒜蓉菜心', price: 13.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-202', name: '虎皮尖椒', price: 15.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-203', name: '蒜蓉油麦菜', price: 12.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-204', name: '蒜蓉空心菜', price: 12.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-205', name: '麻婆豆腐', price: 13.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-206', name: '家常豆腐', price: 15.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-207', name: '蚂蚁上树', price: 18.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-208', name: '干煸四季豆', price: 15.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-209', name: '回锅肉', price: 25.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-210', name: '青椒炒鸡', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-211', name: '泡椒脆肚', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-212', name: '酸甜排骨', price: 45.00, category: '精美小炒', sortOrder: 0 },

  { id: 'dish-213', name: '爆炒排骨', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-214', name: '爆炒猪肚', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-215', name: '蒜苗回锅肉', price: 28.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-216', name: '粉蒸肉', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-217', name: '粉蒸排骨', price: 55.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-218', name: '红烧排骨', price: 45.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-219', name: '小炒猪肝', price: 25.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-220', name: '千页豆腐回锅肉', price: 25.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-221', name: '泡椒猪肝', price: 28.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-222', name: '爆炒猪肝', price: 25.00, category: '精美小炒', sortOrder: 0 },
  
  { id: 'dish-223', name: '鱼香肉丝', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-224', name: '青椒炒排骨', price: 35.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-225', name: '农家小炒肉', price: 25.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-226', name: '烟笋炒腊肉', price: 35.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-227', name: '干豆角炒腊肉', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-228', name: '盐煎肉', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-229', name: '扣肉', price: 35.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-230', name: '辣子鸡', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-231', name: '土匪猪肝', price: 30.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-232', name: '椒盐虾', price: 38.00, category: '精美小炒', sortOrder: 0 },

  { id: 'dish-233', name: '香辣虾', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-234', name: '剁椒蒸黄骨鱼', price: 48.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-235', name: '大盘鸡', price: 38.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-236', name: '红烧猪脚', price: 40.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-237', name: '蒜香骨', price: 48.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-238', name: '红烧甲鱼', price: 68.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-239', name: '土豆烧排骨', price: 48.00, category: '精美小炒', sortOrder: 0 },
  { id: 'dish-240', name: '土豆', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-241', name: '猪血', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-242', name: '生菜', price: 10.00, category: '火锅配菜', sortOrder: 0 },

  { id: 'dish-243', name: '大白菜', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-244', name: '白萝卜', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-245', name: '上海青', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-246', name: '油麦菜', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-247', name: '菠菜', price: 12.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-248', name: '菜心', price: 12.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-249', name: '香菇', price: 14.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-250', name: '金针菇', price: 14.00, category: '火锅配菜', sortOrder: 0 },

  { id: 'dish-251', name: '香菇贡丸', price: 15.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-252', name: '猪肝', price: 25.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-253', name: '冬瓜', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-254', name: '豆芽', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-255', name: '豆腐', price: 10.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-256', name: '千张皮', price: 12.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-257', name: '莲藕', price: 12.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-258', name: '莴笋', price: 12.00, category: '火锅配菜', sortOrder: 0 },

  { id: 'dish-259', name: '红薯粉', price: 14.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-260', name: '平菇', price: 14.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-261', name: '火腿片', price: 14.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-262', name: '鱼丸', price: 15.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-263', name: '猪丸', price: 30.00, category: '火锅配菜', sortOrder: 0 },
  { id: 'dish-264', name: '牛肉丸', price: 20.00, category: '火锅配菜', sortOrder: 0 },

  // 铁板类 (Teppanyaki / Iron Plate)
  { id: 'dish-69', name: '铁板水晶粉', price: 25.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-70', name: '铁板肥肠', price: 40.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-71', name: '铁板鸡块', price: 32.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-72', name: '铁板田鸡', price: 40.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-73', name: '铁板牛肉', price: 45.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-74', name: '铁板猪肚', price: 38.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-75', name: '铁板腰花', price: 42.00, category: '铁板类', sortOrder: 0 },
  { id: 'dish-76', name: '铁板黑胡椒牛肉', price: 45.00, category: '铁板类', sortOrder: 0 },
  // 火锅/鸡煲 (Hot Pot / Chicken Pot)
  { id: 'dish-77', name: '鱼头火锅', price: 68.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-78', name: '鱼火锅', price: 60.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-79', name: '啤酒鸭火锅', price: 75.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-80', name: '排骨火锅', price: 98.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-81', name: '猪脚火锅', price: 88.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-82', name: '腊猪脚汤锅', price: 108.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-83', name: '腊鸭汤锅', price: 75.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-84', name: '腊排骨汤锅', price: 108.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-85', name: '牛杂火锅', price: 98.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-86', name: '牛肚火锅', price: 108.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-87', name: '烧鸡公火锅', price: 75.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-88', name: '牛腩火锅', price: 98.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-89', name: '狗肉火锅', price: 148.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-90', name: '羊肉火锅', price: 138.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-91', name: '麻辣烤鱼', price: 58.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-92', name: '香辣烤鱼', price: 58.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-93', name: '泡椒烤鱼', price: 65.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-94', name: '甲鱼鸡煲', price: 148.00, category: '火锅/鸡煲', sortOrder: 0 },
  { id: 'dish-2001', name: '拍黄瓜', price: 12.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2002', name: '凉拌皮蛋', price: 15.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2003', name: '凉拌金针菇', price: 18.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2004', name: '凉拌猪耳', price: 28.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2005', name: '夫妻肺片', price: 28.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2006', name: '无骨鸡爪', price: 25.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2007', name: '凉拌毛肚', price: 38.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2008', name: '凉拌千张', price: 12.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2009', name: '凉拌猪肚', price: 38.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2010', name: '凉拌猪舌', price: 38.00, category: '凉拌类', sortOrder: 0 },
  { id: 'dish-2011', name: '凉拌牛肉', price: 45.00, category: '凉拌类', sortOrder: 0 },
];

// 干锅类 (Dry Pot)
export const dryPotDishes: Dish[] = [
  { id: 'dish-174', name: '干锅猪脚', price: 40.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-175', name: '干锅啤酒鸭', price: 35.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-176', name: '干锅鸡', price: 35.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-177', name: '干锅腊肉', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-177-1', name: '干锅田鸡', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-178', name: '干锅猪肚', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-179', name: '干锅猪尾', price: 42.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-180', name: '干锅千页豆腐', price: 25.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-181', name: '干锅牛杂', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-182', name: '干锅牛肉', price: 45.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-183', name: '干锅带皮黄牛肉', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-184', name: '干锅排骨', price: 42.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-185', name: '干锅泥鳅', price: 40.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-186', name: '干锅腊排骨', price: 45.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-187', name: '干锅包菜', price: 18.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-188', name: '干锅土豆', price: 20.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-189', name: '干锅脆肚', price: 40.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-189-1', name: '干锅牛蹄', price: 45.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-190', name: '干锅肥肠', price: 42.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-191', name: '干锅黄骨鱼', price: 48.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-192', name: '干锅茶树菇', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-193', name: '干锅羊杂', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-194', name: '干锅虾', price: 38.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-195', name: '干锅腊猪脚', price: 45.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-196', name: '干锅花菜', price: 20.00, category: '干锅类', sortOrder: 0 },
  { id: 'dish-197', name: '干锅鱼肚', price: 58.00, category: '干锅类', sortOrder: 0 },
];

initialDishes.push(...dryPotDishes)

export const initialTables: Table[] = [
  { id: 'table-1', number: '1', order: [] },
  { id: 'table-2', number: '2', order: [] },
  { id: 'table-3', number: '3', order: [] },
  { id: 'table-4', number: '4', order: [] },
  { id: 'table-5', number: '5', order: [] },
  { id: 'table-6', number: '6', order: [] },
  { id: 'table-7', number: '7', order: [] },
  { id: 'table-takeout', number: '外卖', order: [] },
];
